### PR TITLE
add 1.7.0 and 1.8.0

### PR DESCRIPTION
**Pull request by Futuremappermydud**

### CODE REVIEW

**Comment by raftario** [comment]
I won't merge this until the template is made compatible with the new beatsaber-hook and 1.8.0, which it isn't.

**Comment by Futuremappermydud** [comment]
ok

**Comment by raftario** [comment]
Template has been updated, if you want to add 1.9 I'll merge !

**Comment by Futuremappermydud** [comment]
@raftario

**Comment by Futuremappermydud** [comment]
:D

**Pull request merged**
